# Generated by Django 5.2.5 on 2025-08-31 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.disciplina')),
            ],
            options={
                'unique_together': {('nome', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('enunciado', models.TextField()),
                ('alternativas', models.JSONField()),
                ('gabarito', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('explicacao', models.TextField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, max_length=100, null=True)),
                ('is_inedita', models.BooleanField(default=False, verbose_name='É inédita?')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.assunto')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.banca')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.disciplina')),
            ],
        ),
    ]
