# Generated by Django 5.2.5 on 2025-09-20 19:14

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.disciplina')),
            ],
            options={
                'unique_together': {('nome', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('imagem_enunciado', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='enunciado_pics/')),
                ('enunciado', models.TextField()),
                ('alternativas', models.JSONField()),
                ('gabarito', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('explicacao', models.TextField(blank=True, null=True)),
                ('is_inedita', models.BooleanField(default=False, verbose_name='É inédita?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.assunto')),
                ('banca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questoes.banca')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes_deletadas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.disciplina')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questoes.instituicao')),
            ],
        ),
    ]
