# Generated by Django 5.2.5 on 2025-09-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_remove_questao_fonte_questao_criada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='imagem_enunciado',
            field=models.ImageField(blank=True, null=True, upload_to='enunciado_pics/'),
        ),
    ]
