# Generated by Django 5.2.5 on 2025-09-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0004_instituicao_questao_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
