# Generated by Django 5.2.5 on 2025-09-09 19:42

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0005_questao_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='imagem_enunciado',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='enunciado_pics/'),
        ),
    ]
