# Generated by Django 5.2.5 on 2025-09-20 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('questoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='comentarios_curtidos', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='pratica.comentario')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='questoes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='FiltroSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('parametros_url', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_erro', models.CharField(choices=[('ENUNCIADO_ALTERNATIVA', 'Enunciado/alternativa errada'), ('DISCIPLINA_ASSUNTO', 'Disciplina ou assunto errado'), ('QUESTAO_ANULADA', 'Questão anulada'), ('QUESTAO_DESATUALIZADA', 'Questão desatualizada'), ('QUESTAO_DUPLICADA', 'Questão duplicada'), ('COMENTARIO_OFENSIVO', 'Conteúdo ofensivo ou inadequado'), ('COMENTARIO_SPAM', 'Spam ou propaganda'), ('COMENTARIO_OUTRO', 'Outro problema no comentário')], max_length=50)),
                ('descricao', models.TextField(verbose_name='Descrição do erro')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDO', 'Resolvido'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_temp', to='questoes.questao')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_resolvidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação/Denúncia',
                'verbose_name_plural': 'Notificações & Denúncias',
                'ordering': ['-data_criacao'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDENTE')), fields=('content_type', 'object_id', 'usuario_reportou'), name='unique_active_report_per_user_per_object')],
            },
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_selecionada', models.CharField(max_length=1)),
                ('foi_correta', models.BooleanField()),
                ('data_resposta', models.DateTimeField(auto_now=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'questao')},
            },
        ),
    ]
