# Generated by Django 5.2.5 on 2025-09-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratica', '0005_comentario_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['data_criacao']},
        ),
    ]
