# Generated by Django 5.2.5 on 2025-09-06 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratica', '0006_alter_comentario_options'),
        ('questoes', '0005_questao_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_erro', models.CharField(choices=[('ENUNCIADO_ALTERNATIVA', 'Enunciado/alternativa errada'), ('DISCIPLINA_ASSUNTO', 'Disciplina ou assunto errado'), ('QUESTAO_ANULADA', 'Questão anulada'), ('QUESTAO_DESATUALIZADA', 'Questão desatualizada'), ('QUESTAO_DUPLICADA', 'Questão duplicada')], max_length=50)),
                ('descricao', models.TextField(verbose_name='Descrição do erro')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDO', 'Resolvido')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='questoes.questao')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_resolvidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
