# Generated by Django 5.2.5 on 2025-09-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratica', '0007_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDO', 'Resolvido'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=20),
        ),
    ]
