# Generated by Django 5.2.5 on 2025-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratica', '0008_alter_notificacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='data_arquivamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
