# Generated by Django 5.2.5 on 2025-09-07 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratica', '0010_limpar_notificacoes_duplicadas'),
        ('questoes', '0005_questao_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido'), ('REJEITADO', 'Rejeitado'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDENTE', 'EM_ANALISE'])), fields=('questao', 'usuario_reportou'), name='unique_active_report_per_user_per_question'),
        ),
    ]
