# Generated by Django 5.2.5 on 2025-09-07 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratica', '0011_alter_notificacao_status_and_more'),
        ('questoes', '0005_questao_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificacao',
            name='unique_active_report_per_user_per_question',
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDO', 'Corrigido'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDENTE')), fields=('questao', 'usuario_reportou'), name='unique_active_report_per_user_per_question'),
        ),
    ]
