# Generated by Django 5.2.5 on 2025-09-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratica', '0012_remove_notificacao_unique_active_report_per_user_per_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='data_arquivamento',
        ),
    ]
