# Generated by Django 5.2.5 on 2025-09-12 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pratica', '0013_remove_notificacao_data_arquivamento'),
        ('questoes', '0007_questao_deleted_at_questao_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Notificação/Denúncia', 'verbose_name_plural': 'Notificações & Denúncias'},
        ),
        migrations.RemoveConstraint(
            model_name='notificacao',
            name='unique_active_report_per_user_per_question',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='questao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_temp', to='questoes.questao'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDO', 'Resolvido'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo_erro',
            field=models.CharField(choices=[('ENUNCIADO_ALTERNATIVA', 'Enunciado/alternativa errada'), ('DISCIPLINA_ASSUNTO', 'Disciplina ou assunto errado'), ('QUESTAO_ANULADA', 'Questão anulada'), ('QUESTAO_DESATUALIZADA', 'Questão desatualizada'), ('QUESTAO_DUPLICADA', 'Questão duplicada'), ('COMENTARIO_OFENSIVO', 'Conteúdo ofensivo ou inadequado'), ('COMENTARIO_SPAM', 'Spam ou propaganda'), ('COMENTARIO_OUTRO', 'Outro problema no comentário')], max_length=50),
        ),
    ]
