# Generated by Django 5.2.5 on 2025-09-12 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pratica', '0014_alter_notificacao_options_and_more'),
        ('questoes', '0007_questao_deleted_at_questao_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDENTE')), fields=('content_type', 'object_id', 'usuario_reportou'), name='unique_active_report_per_user_per_object'),
        ),
    ]
