# Generated by Django 5.2.5 on 2025-09-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratica', '0015_notificacao_unique_active_report_per_user_per_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostausuario',
            name='data_resposta',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
