# Generated by Django 5.2.5 on 2025-09-12 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questoes', '0007_questao_deleted_at_questao_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('questoes', models.ManyToManyField(to='questoes.questao')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulados.simulado')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_selecionada', models.CharField(blank=True, max_length=1, null=True)),
                ('foi_correta', models.BooleanField(blank=True, null=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='simulados.sessaosimulado')),
            ],
            options={
                'unique_together': {('sessao', 'questao')},
            },
        ),
    ]
