# Generated by Django 5.2.5 on 2025-09-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='is_oficial',
            field=models.BooleanField(default=False, verbose_name='É um simulado oficial?'),
        ),
    ]
