# Generated by Django 5.2.5 on 2025-09-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0007_questao_deleted_at_questao_deleted_by_and_more'),
        ('simulados', '0002_simulado_is_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='filtros_iniciais',
            field=models.JSONField(blank=True, help_text='Filtros usados na criação para definir o pool de questões.', null=True),
        ),
        migrations.AlterField(
            model_name='simulado',
            name='questoes',
            field=models.ManyToManyField(blank=True, to='questoes.questao'),
        ),
    ]
