# Generated by Django 5.2.5 on 2025-09-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0003_simulado_filtros_iniciais_alter_simulado_questoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='simulado',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('EM_BREVE', 'Em Breve'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=10),
        ),
    ]
