# Generated by Django 5.2.5 on 2025-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0004_simulado_codigo_simulado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulado',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único do simulado, gerado automaticamente.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='simulado',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('EM_BREVE', 'Em Breve'), ('ARQUIVADO', 'Arquivado')], db_index=True, default='ATIVO', max_length=10),
        ),
    ]
