# Generated by Django 5.2.5 on 2025-09-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0005_alter_simulado_codigo_alter_simulado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='dificuldade',
            field=models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIO', 'Médio'), ('DIFICIL', 'Difícil')], default='MEDIO', help_text='Visível apenas para simulados oficiais.', max_length=10, verbose_name='Nível de Dificuldade'),
        ),
    ]
