# Generated by Django 5.2.5 on 2025-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0006_simulado_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='tempo_por_questao',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo médio em minutos por questão. Nulo significa tempo ilimitado.', null=True),
        ),
    ]
