# Generated by Django 5.2.5 on 2025-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0007_simulado_tempo_por_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaosimulado',
            name='tempo_restante_segundos',
            field=models.PositiveIntegerField(blank=True, help_text='Armazena o tempo restante em segundos quando o usuário pausa ou sai.', null=True),
        ),
    ]
