# Generated by Django 5.2.5 on 2025-09-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0008_sessaosimulado_tempo_restante_segundos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaosimulado',
            name='tempo_restante_segundos',
        ),
    ]
