# Generated by Django 5.2.5 on 2025-08-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='questoes_favoritas',
            field=models.ManyToManyField(blank=True, to='questoes.questao'),
        ),
    ]
