# Generated by Django 5.2.5 on 2025-09-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0007_avatar_borda_avatarusuario_bordausuario'),
        ('usuarios', '0004_userprofile_foto_perfil_ativacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_equipado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_com_avatar', to='gamificacao.avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='borda_equipada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_com_borda', to='gamificacao.borda'),
        ),
    ]
