# Generated by Django 5.2.5 on 2025-09-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0008_banner_bannerusuario'),
        ('usuarios', '0005_remove_userprofile_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_equipado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_com_banner', to='gamificacao.banner'),
        ),
    ]
