# Generated by Django 5.2.5 on 2025-09-12 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_userprofile_foto_perfil_ativacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(help_text="Ex: 'fas fa-fire' (classes do Font Awesome)", max_length=50)),
                ('cor', models.CharField(default='gold', help_text="Cor do ícone (ex: 'gold', '#FFD700')", max_length=20)),
                ('chave', models.CharField(help_text="Identificador único, ex: 'STREAK_7_DIAS'", max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_data', to='usuarios.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConquistaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.conquista')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='usuarios.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'conquista')},
            },
        ),
    ]
