# Generated by Django 5.2.5 on 2025-09-16 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0001_initial'),
        ('usuarios', '0004_userprofile_foto_perfil_ativacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Nível')),
                ('xp', models.IntegerField(default=0, verbose_name='Pontos de Experiência (XP)')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamificacao_data', to='usuarios.userprofile')),
            ],
        ),
    ]
