# Generated by Django 5.2.5 on 2025-09-20 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gamificacao', '0001_initial'),
        ('questoes', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarusuario',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatares_desbloqueados', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='bannerusuario',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.banner'),
        ),
        migrations.AddField(
            model_name='bannerusuario',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners_desbloqueados', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='bordausuario',
            name='borda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.borda'),
        ),
        migrations.AddField(
            model_name='bordausuario',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordas_desbloqueadas', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='campanhausuariocompletion',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.campanha'),
        ),
        migrations.AddField(
            model_name='campanhausuariocompletion',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile'),
        ),
        migrations.CreateModel(
            name='CondicaoStreak',
            fields=[
                ('condicao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gamificacao.condicao')),
                ('dias_consecutivos', models.PositiveIntegerField(default=3, help_text='Número de dias consecutivos de prática necessários.')),
            ],
            bases=('gamificacao.condicao',),
        ),
        migrations.AddField(
            model_name='conquista',
            name='pre_requisitos',
            field=models.ManyToManyField(blank=True, related_name='desbloqueia', to='gamificacao.conquista', verbose_name='Pré-requisitos'),
        ),
        migrations.AddField(
            model_name='condicao',
            name='conquista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes', to='gamificacao.conquista'),
        ),
        migrations.AddField(
            model_name='borda',
            name='conquista_necessaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista'),
        ),
        migrations.AddField(
            model_name='banner',
            name='conquista_necessaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='conquista_necessaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista'),
        ),
        migrations.AddField(
            model_name='conquistausuario',
            name='conquista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.conquista'),
        ),
        migrations.AddField(
            model_name='conquistausuario',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='metadiariausuario',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_diarias', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='profilegamificacao',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamificacao_data', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='profilestreak',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_data', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='rankingmensal',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='rankingsemanal',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='recompensapendente',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='recompensapendente',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_pendentes', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='recompensausuario',
            name='concedido_por',
            field=models.ForeignKey(blank=True, help_text='Admin que concedeu manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recompensausuario',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='recompensausuario',
            name='origem_campanha',
            field=models.ForeignKey(blank=True, help_text='Campanha que concedeu o prêmio.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.campanha'),
        ),
        migrations.AddField(
            model_name='recompensausuario',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_ganhas', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='condicao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamificacao.tipocondicao'),
        ),
        migrations.AddField(
            model_name='conquista',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conquistas', to='gamificacao.trilhadeconquistas'),
        ),
        migrations.AlterUniqueTogether(
            name='avatarusuario',
            unique_together={('user_profile', 'avatar')},
        ),
        migrations.AlterUniqueTogether(
            name='bannerusuario',
            unique_together={('user_profile', 'banner')},
        ),
        migrations.AlterUniqueTogether(
            name='bordausuario',
            unique_together={('user_profile', 'borda')},
        ),
        migrations.AlterUniqueTogether(
            name='campanhausuariocompletion',
            unique_together={('user_profile', 'campanha', 'ciclo_id')},
        ),
        migrations.CreateModel(
            name='CondicaoVolumeQuestoes',
            fields=[
                ('condicao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gamificacao.condicao')),
                ('quantidade', models.PositiveIntegerField(default=10, help_text='Número total de questões a serem resolvidas.')),
                ('percentual_acerto_minimo', models.PositiveIntegerField(default=0, help_text='De 0 a 100. Deixe 0 para ignorar.')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questoes.assunto')),
                ('banca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questoes.banca')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questoes.disciplina')),
            ],
            bases=('gamificacao.condicao',),
        ),
        migrations.AlterUniqueTogether(
            name='conquistausuario',
            unique_together={('user_profile', 'conquista')},
        ),
        migrations.AlterUniqueTogether(
            name='metadiariausuario',
            unique_together={('user_profile', 'data')},
        ),
        migrations.AlterUniqueTogether(
            name='rankingmensal',
            unique_together={('user_profile', 'ano', 'mes')},
        ),
        migrations.AlterUniqueTogether(
            name='rankingsemanal',
            unique_together={('user_profile', 'ano', 'semana')},
        ),
        migrations.AlterUniqueTogether(
            name='recompensapendente',
            unique_together={('user_profile', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='recompensausuario',
            index=models.Index(fields=['content_type', 'object_id'], name='gamificacao_content_ef5b0c_idx'),
        ),
    ]
