# Generated by Django 5.2.5 on 2025-09-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0002_profilegamificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilegamificacao',
            name='acertos_consecutivos',
            field=models.IntegerField(default=0, verbose_name='Acertos Consecutivos'),
        ),
    ]
