# Generated by Django 5.2.5 on 2025-09-20 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDesbloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('NIVEL', 'Por Nível'), ('CONQUISTA', 'Por Conquista'), ('EVENTO', 'Evento / Manual'), ('CAMPANHA', 'Campanha'), ('LOJA', 'Comprável na Loja')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='tipo_desbloqueio',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='tipo_desbloqueio',
        ),
        migrations.RemoveField(
            model_name='borda',
            name='tipo_desbloqueio',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='conquista_necessaria',
            field=models.ForeignKey(blank=True, help_text='Preencha se for desbloqueável por conquista.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='nivel_necessario',
            field=models.PositiveIntegerField(blank=True, help_text='Preencha se for desbloqueável por nível.', null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='preco_moedas',
            field=models.PositiveIntegerField(default=0, help_text='Preencha se for comprável na loja.', verbose_name='Preço em Moedas'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='conquista_necessaria',
            field=models.ForeignKey(blank=True, help_text='Preencha se for desbloqueável por conquista.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='nivel_necessario',
            field=models.PositiveIntegerField(blank=True, help_text='Preencha se for desbloqueável por nível.', null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='preco_moedas',
            field=models.PositiveIntegerField(default=0, help_text='Preencha se for comprável na loja.', verbose_name='Preço em Moedas'),
        ),
        migrations.AlterField(
            model_name='borda',
            name='conquista_necessaria',
            field=models.ForeignKey(blank=True, help_text='Preencha se for desbloqueável por conquista.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista'),
        ),
        migrations.AlterField(
            model_name='borda',
            name='nivel_necessario',
            field=models.PositiveIntegerField(blank=True, help_text='Preencha se for desbloqueável por nível.', null=True),
        ),
        migrations.AlterField(
            model_name='borda',
            name='preco_moedas',
            field=models.PositiveIntegerField(default=0, help_text='Preencha se for comprável na loja.', verbose_name='Preço em Moedas'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='tipos_desbloqueio',
            field=models.ManyToManyField(blank=True, to='gamificacao.tipodesbloqueio', verbose_name='Formas de Desbloqueio'),
        ),
        migrations.AddField(
            model_name='banner',
            name='tipos_desbloqueio',
            field=models.ManyToManyField(blank=True, to='gamificacao.tipodesbloqueio', verbose_name='Formas de Desbloqueio'),
        ),
        migrations.AddField(
            model_name='borda',
            name='tipos_desbloqueio',
            field=models.ManyToManyField(blank=True, to='gamificacao.tipodesbloqueio', verbose_name='Formas de Desbloqueio'),
        ),
    ]
