# Generated by Django 5.2.5 on 2025-09-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0003_tipodesbloqueio_remove_avatar_tipo_desbloqueio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='preco_moedas',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Preencha se for comprável na loja.', null=True, verbose_name='Preço em Moedas'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='preco_moedas',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Preencha se for comprável na loja.', null=True, verbose_name='Preço em Moedas'),
        ),
        migrations.AlterField(
            model_name='borda',
            name='preco_moedas',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Preencha se for comprável na loja.', null=True, verbose_name='Preço em Moedas'),
        ),
    ]
