# Generated by Django 5.2.5 on 2025-09-16 20:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0003_profilegamificacao_acertos_consecutivos'),
        ('usuarios', '0004_userprofile_foto_perfil_ativacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDiariaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('questoes_resolvidas', models.PositiveIntegerField(default=0)),
                ('meta_atingida', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_diarias', to='usuarios.userprofile')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('user_profile', 'data')},
            },
        ),
    ]
