# Generated by Django 5.2.5 on 2025-09-21 15:16

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0004_alter_avatar_preco_moedas_alter_banner_preco_moedas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='conquista_necessaria',
            field=models.ForeignKey(blank=True, help_text='Preencha se for desbloqueável por conquista.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista', verbose_name='Conquista Necessária'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='descricao',
            field=models.CharField(help_text='Como desbloquear este item.', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagem',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='gamificacao_recompensas/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='nivel_necessario',
            field=models.PositiveIntegerField(blank=True, help_text='Preencha se for desbloqueável por nível.', null=True, verbose_name='Nível Necessário'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='raridade',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('RARO', 'Raro'), ('EPICO', 'Épico'), ('LENDARIO', 'Lendário'), ('MITICO', 'Mítico')], default='COMUM', max_length=20, verbose_name='Raridade'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='conquista_necessaria',
            field=models.ForeignKey(blank=True, help_text='Preencha se for desbloqueável por conquista.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista', verbose_name='Conquista Necessária'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='descricao',
            field=models.CharField(help_text='Como desbloquear este item.', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='gamificacao_recompensas/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='nivel_necessario',
            field=models.PositiveIntegerField(blank=True, help_text='Preencha se for desbloqueável por nível.', null=True, verbose_name='Nível Necessário'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='raridade',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('RARO', 'Raro'), ('EPICO', 'Épico'), ('LENDARIO', 'Lendário'), ('MITICO', 'Mítico')], default='COMUM', max_length=20, verbose_name='Raridade'),
        ),
        migrations.AlterField(
            model_name='borda',
            name='conquista_necessaria',
            field=models.ForeignKey(blank=True, help_text='Preencha se for desbloqueável por conquista.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista', verbose_name='Conquista Necessária'),
        ),
        migrations.AlterField(
            model_name='borda',
            name='descricao',
            field=models.CharField(help_text='Como desbloquear este item.', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='borda',
            name='imagem',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='gamificacao_recompensas/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='borda',
            name='nivel_necessario',
            field=models.PositiveIntegerField(blank=True, help_text='Preencha se for desbloqueável por nível.', null=True, verbose_name='Nível Necessário'),
        ),
        migrations.AlterField(
            model_name='borda',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='borda',
            name='raridade',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('RARO', 'Raro'), ('EPICO', 'Épico'), ('LENDARIO', 'Lendário'), ('MITICO', 'Mítico')], default='COMUM', max_length=20, verbose_name='Raridade'),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='gamificacao.trilhadeconquistas'),
        ),
    ]
