# Generated by Django 5.2.5 on 2025-09-16 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0004_metadiariausuario'),
        ('usuarios', '0004_userprofile_foto_perfil_ativacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('acertos_periodo', models.PositiveIntegerField(default=0)),
                ('respostas_periodo', models.PositiveIntegerField(default=0)),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile')),
            ],
            options={
                'verbose_name': 'Ranking Mensal',
                'verbose_name_plural': 'Rankings Mensais',
                'ordering': ['posicao'],
                'abstract': False,
                'unique_together': {('user_profile', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='RankingSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('acertos_periodo', models.PositiveIntegerField(default=0)),
                ('respostas_periodo', models.PositiveIntegerField(default=0)),
                ('ano', models.PositiveIntegerField()),
                ('semana', models.PositiveIntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile')),
            ],
            options={
                'verbose_name': 'Ranking Semanal',
                'verbose_name_plural': 'Rankings Semanais',
                'ordering': ['posicao'],
                'abstract': False,
                'unique_together': {('user_profile', 'ano', 'semana')},
            },
        ),
    ]
