# Generated by Django 5.2.5 on 2025-09-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0005_rankingmensal_rankingsemanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaAgendadaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(choices=[('gerar_ranking_semanal', 'Gerar Ranking Semanal'), ('gerar_ranking_mensal', 'Gerar Ranking Mensal')], max_length=50, unique=True)),
                ('ultima_execucao', models.DateTimeField()),
            ],
        ),
    ]
