# Generated by Django 5.2.5 on 2025-09-21 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0005_alter_avatar_conquista_necessaria_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariavelDoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(help_text='Ex: Total de Acertos, Recorde de Streak', max_length=100, verbose_name='Nome para o Admin')),
                ('chave', models.CharField(help_text="Chave interna usada pelo sistema. Ex: 'total_acertos'", max_length=50, unique=True)),
                ('descricao', models.TextField(help_text='Explicação de como esta variável é calculada.')),
            ],
            options={
                'verbose_name': 'Variável do Jogo',
                'verbose_name_plural': 'Variáveis do Jogo',
                'ordering': ['nome_exibicao'],
            },
        ),
        migrations.RemoveField(
            model_name='condicaovolumequestoes',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='condicaovolumequestoes',
            name='banca',
        ),
        migrations.RemoveField(
            model_name='condicaovolumequestoes',
            name='condicao_ptr',
        ),
        migrations.RemoveField(
            model_name='condicaovolumequestoes',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='condicao',
            name='tipo',
        ),
        migrations.AlterModelOptions(
            name='condicao',
            options={'verbose_name': 'Condição', 'verbose_name_plural': 'Condições'},
        ),
        migrations.RemoveField(
            model_name='condicao',
            name='parametros_valores',
        ),
        migrations.AddField(
            model_name='condicao',
            name='contexto_json',
            field=models.JSONField(blank=True, default=dict, help_text="Opcional. Use para filtrar variáveis. Ex: {'disciplina_id': 5}", verbose_name='Filtros Adicionais (JSON)'),
        ),
        migrations.AddField(
            model_name='condicao',
            name='operador',
            field=models.CharField(choices=[('>=', 'Maior ou igual a'), ('<=', 'Menor ou igual a'), ('==', 'Igual a'), ('!=', 'Diferente de')], default='>=', max_length=4),
        ),
        migrations.AddField(
            model_name='condicao',
            name='valor',
            field=models.IntegerField(default=0, verbose_name='Valor para comparar'),
        ),
        migrations.AlterField(
            model_name='conquistausuario',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas_usuario', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='condicao',
            name='variavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.variaveldojogo', verbose_name='Variável a ser verificada'),
        ),
        migrations.DeleteModel(
            name='CondicaoStreak',
        ),
        migrations.DeleteModel(
            name='CondicaoVolumeQuestoes',
        ),
        migrations.DeleteModel(
            name='TipoCondicao',
        ),
    ]
