# Generated by Django 5.2.5 on 2025-09-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0006_variaveldojogo_remove_condicaovolumequestoes_assunto_and_more'),
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='simulado_especifico',
            field=models.ForeignKey(blank=True, help_text='Se um simulado for selecionado, esta campanha só será ativada pela conclusão dele.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulados.simulado', verbose_name='Simulado Específico (Opcional)'),
        ),
    ]
