# Generated by Django 5.2.5 on 2025-09-17 12:36

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0006_tarefaagendadalog'),
        ('usuarios', '0004_userprofile_foto_perfil_ativacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(help_text='Como desbloquear este item.', max_length=255)),
                ('imagem', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='gamificacao_recompensas/')),
                ('tipo_desbloqueio', models.CharField(choices=[('NIVEL', 'Por Nível'), ('CONQUISTA', 'Por Conquista'), ('EVENTO', 'Evento Especial')], max_length=20)),
                ('nivel_necessario', models.PositiveIntegerField(blank=True, null=True)),
                ('conquista_necessaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Borda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(help_text='Como desbloquear este item.', max_length=255)),
                ('imagem', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='gamificacao_recompensas/')),
                ('tipo_desbloqueio', models.CharField(choices=[('NIVEL', 'Por Nível'), ('CONQUISTA', 'Por Conquista'), ('EVENTO', 'Evento Especial')], max_length=20)),
                ('nivel_necessario', models.PositiveIntegerField(blank=True, null=True)),
                ('conquista_necessaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificacao.conquista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvatarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_desbloqueio', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.avatar')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatares_desbloqueados', to='usuarios.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'avatar')},
            },
        ),
        migrations.CreateModel(
            name='BordaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_desbloqueio', models.DateTimeField(auto_now_add=True)),
                ('borda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.borda')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordas_desbloqueadas', to='usuarios.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'borda')},
            },
        ),
    ]
