# Generated by Django 5.2.5 on 2025-09-22 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0007_campanha_simulado_especifico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='gatilho',
            field=models.CharField(choices=[('COMPLETAR_SIMULADO', 'Ao Completar um Simulado'), ('RANKING_SEMANAL_CONCLUIDO', 'Ao Fechar o Ranking Semanal'), ('RANKING_MENSAL_CONCLUIDO', 'Ao Fechar o Ranking Mensal'), ('PRIMEIRA_ACAO_DO_DIA', 'Na Primeira Ação do Dia'), ('META_DIARIA_CONCLUIDA', 'Ao Concluir a Meta Diária')], max_length=50, verbose_name='Gatilho de Ativação'),
        ),
        migrations.CreateModel(
            name='ConquistaDiariaGlobalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('META_DIARIA', 'Primeiro a Concluir a Meta Diária')], max_length=50)),
                ('conquistado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('data', 'tipo')},
            },
        ),
    ]
