# Generated by Django 5.2.5 on 2025-09-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0008_banner_bannerusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadiariausuario',
            name='xp_ganho_dia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
