# Generated by Django 5.2.5 on 2025-09-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0009_metadiariausuario_xp_ganho_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_por_acerto', models.PositiveIntegerField(default=10, help_text='XP ganho por cada questão respondida corretamente.')),
                ('xp_por_erro', models.PositiveIntegerField(default=1, help_text='XP ganho por cada questão respondida incorretamente.')),
                ('xp_bonus_meta_diaria', models.PositiveIntegerField(default=50, help_text='Bônus de XP por completar a meta diária.')),
                ('meta_diaria_questoes', models.PositiveIntegerField(default=15, help_text='Número de questões para atingir a meta diária.')),
                ('acertos_consecutivos_para_bonus', models.PositiveIntegerField(default=5, help_text='Número de acertos consecutivos para ativar o bônus de XP em dobro.')),
            ],
            options={
                'verbose_name': 'Configurações de Gamificação',
                'verbose_name_plural': 'Configurações de Gamificação',
            },
        ),
        migrations.AlterModelOptions(
            name='avatar',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='borda',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='avatar',
            name='raridade',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('RARO', 'Raro'), ('EPICO', 'Épico'), ('LENDARIO', 'Lendário'), ('MITICO', 'Mítico')], default='COMUM', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='raridade',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('RARO', 'Raro'), ('EPICO', 'Épico'), ('LENDARIO', 'Lendário'), ('MITICO', 'Mítico')], default='COMUM', max_length=20),
        ),
        migrations.AddField(
            model_name='borda',
            name='raridade',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('RARO', 'Raro'), ('EPICO', 'Épico'), ('LENDARIO', 'Lendário'), ('MITICO', 'Mítico')], default='COMUM', max_length=20),
        ),
        migrations.AddField(
            model_name='profilegamificacao',
            name='bonus_xp_ativo',
            field=models.BooleanField(default=False, help_text='Indica se o bônus de XP em dobro está ativo.'),
        ),
    ]
