# Generated by Django 5.2.5 on 2025-09-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0009_alter_campanha_gatilho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='gatilho',
            field=models.CharField(choices=[('COMPLETAR_SIMULADO', 'Ao Completar um Simulado'), ('RANKING_SEMANAL_CONCLUIDO', 'Ao Fechar o Ranking Semanal'), ('RANKING_MENSAL_CONCLUIDO', 'Ao Fechar o Ranking Mensal'), ('PRIMEIRA_ACAO_DO_DIA', 'Na Primeira Ação do Dia'), ('META_DIARIA_CONCLUIDA', 'Ao Concluir a Meta Diária'), ('CONQUISTA_DESBLOQUEADA', 'Ao Desbloquear uma Conquista'), ('COMENTARIO_PUBLICADO', 'Ao Publicar um Comentário')], max_length=50, verbose_name='Gatilho de Ativação'),
        ),
    ]
