# Generated by Django 5.2.5 on 2025-09-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0010_gamificationsettings_alter_avatar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background_position',
            field=models.CharField(default='center 50%', help_text="Define o ponto focal da imagem (ex: 'center 50%', 'top 20%', 'right bottom').", max_length=50),
        ),
    ]
