# Generated by Django 5.2.5 on 2025-09-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0011_alter_campanha_gatilho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='conquista_necessaria',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='conquista_necessaria',
        ),
        migrations.RemoveField(
            model_name='borda',
            name='conquista_necessaria',
        ),
    ]
