# Generated by Django 5.2.5 on 2025-09-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0011_banner_background_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background_size',
            field=models.CharField(default='cover', help_text="Define o nível de zoom da imagem (ex: '120%').", max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='background_position',
            field=models.CharField(default='50% 50%', help_text="Define o ponto focal da imagem (ex: '50% 50%').", max_length=50),
        ),
    ]
