# Generated by Django 5.2.5 on 2025-09-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0012_banner_background_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='background_position',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='background_size',
        ),
    ]
