# Generated by Django 5.2.5 on 2025-09-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0012_remove_avatar_conquista_necessaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilhadeconquistas',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição das trilhas (menor primeiro). Cada trilha deve ter uma ordem única.', unique=True, verbose_name='Ordem de Exibição'),
        ),
    ]
