# Generated by Django 5.2.5 on 2025-09-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0013_alter_trilhadeconquistas_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conquista',
            options={'ordering': ['trilha__ordem', 'serie__ordem', 'ordem_na_serie', 'nome']},
        ),
        migrations.AddField(
            model_name='conquista',
            name='ordem_na_serie',
            field=models.PositiveIntegerField(default=0, help_text='Ordem gerenciada pelo sistema dentro de uma série.'),
        ),
        migrations.CreateModel(
            name='SerieDeConquistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Série')),
                ('descricao', models.TextField(help_text='Um breve resumo do objetivo desta série de conquistas.', verbose_name='Descrição da Série')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição das séries dentro da trilha.')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='gamificacao.trilhadeconquistas')),
            ],
            options={
                'verbose_name': 'Série de Conquistas',
                'verbose_name_plural': 'Séries de Conquistas',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('trilha', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='conquista',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conquistas_da_serie', to='gamificacao.seriedeconquistas'),
        ),
    ]
