# Generated by Django 5.2.5 on 2025-09-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0013_remove_banner_background_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationsettings',
            name='habilitar_teto_xp_diario',
            field=models.BooleanField(default=True, help_text='Se marcado, limita a quantidade de XP que um usuário pode ganhar por dia para evitar farming.', verbose_name='Habilitar Teto de XP Diário?'),
        ),
        migrations.AddField(
            model_name='gamificationsettings',
            name='teto_xp_diario',
            field=models.PositiveIntegerField(default=500, help_text='Quantidade máxima de XP que pode ser ganha em 24 horas, se o teto estiver habilitado.', verbose_name='Teto de XP Diário'),
        ),
    ]
