# Generated by Django 5.2.5 on 2025-09-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0014_alter_conquista_options_conquista_ordem_na_serie_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seriedeconquistas',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conquista',
            name='sequencia_automatica',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='ordem_na_serie',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conquistas', to='gamificacao.seriedeconquistas', verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='seriedeconquistas',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição da Série'),
        ),
        migrations.AlterField(
            model_name='seriedeconquistas',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome da Série'),
        ),
    ]
