# Generated by Django 5.2.5 on 2025-09-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0014_gamificationsettings_habilitar_teto_xp_diario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationsettings',
            name='cooldown_mesma_questao_horas',
            field=models.PositiveIntegerField(default=24, help_text='Impede que o usuário ganhe XP respondendo à mesma questão várias vezes em um curto período.', verbose_name='Cooldown para ganhar XP na mesma questão (em horas)'),
        ),
        migrations.AddField(
            model_name='gamificationsettings',
            name='tempo_minimo_entre_respostas_segundos',
            field=models.PositiveIntegerField(default=5, help_text='Proteção anti-bot. Respostas mais rápidas que isso não geram XP.', verbose_name='Tempo mínimo entre respostas para ganhar XP (em segundos)'),
        ),
        migrations.AlterField(
            model_name='gamificationsettings',
            name='habilitar_teto_xp_diario',
            field=models.BooleanField(default=True, help_text='Se marcado, limita a quantidade de XP que um usuário pode ganhar por dia.', verbose_name='Habilitar Teto de XP Diário?'),
        ),
    ]
