# Generated by Django 5.2.5 on 2025-10-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0015_alter_seriedeconquistas_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='descricao',
            field=models.TextField(help_text='Como desbloquear este item.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='descricao',
            field=models.TextField(help_text='Como desbloquear este item.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='borda',
            name='descricao',
            field=models.TextField(help_text='Como desbloquear este item.', verbose_name='Descrição'),
        ),
    ]
