# Generated by Django 5.2.5 on 2025-09-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0017_gamificationsettings_bonus_consecutivo_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationsettings',
            name='cooldown_mesmo_simulado_horas',
            field=models.PositiveIntegerField(default=48, help_text='Impede que o usuário ganhe XP finalizando o mesmo simulado várias vezes em um curto período.', verbose_name='Cooldown para ganhar XP no mesmo simulado (em horas)'),
        ),
    ]
