# Generated by Django 5.2.5 on 2025-09-20 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespromocaoSuperuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado_por', models.ManyToManyField(blank=True, related_name='despromocoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despromocoes_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despromocoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExclusaoLogPermanente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('log_ids', models.TextField(help_text='Lista de IDs dos logs a serem excluídos, separados por vírgula.')),
                ('aprovado_por', models.ManyToManyField(blank=True, related_name='exclusoes_log_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusoes_log_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_alvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusoes_log_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExclusaoSuperuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado_por', models.ManyToManyField(blank=True, related_name='exclusoes_superuser_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusoes_superuser_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusoes_superuser_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('USUARIO_DELETADO', 'Usuário Deletado'), ('PERMISSOES_ALTERADAS', 'Permissões de Usuário Alteradas'), ('USUARIO_PROMOVIDO_SUPERUSER', 'Usuário Promovido a Superuser'), ('USUARIO_DESPROMOVIDO_SUPERUSER', 'Usuário Despromovido de Superuser'), ('SOLICITACAO_EXCLUSAO_CRIADA', 'Solicitação de Exclusão Criada'), ('SOLICITACAO_EXCLUSAO_APROVADA', 'Solicitação de Exclusão Aprovada'), ('SOLICITACAO_EXCLUSAO_REJEITADA', 'Solicitação de Exclusão Rejeitada'), ('SOLICITACAO_EXCLUSAO_CANCELADA', 'Solicitação de Exclusão Cancelada'), ('SOLICITACAO_PROMOCAO_CRIADA', 'Solicitação de Promoção Criada'), ('SOLICITACAO_PROMOCAO_APROVADA', 'Aprovação de Promoção Registrada'), ('SOLICITACAO_PROMOCAO_CANCELADA', 'Solicitação de Promoção Cancelada'), ('SOLICITACAO_DESPROMOCAO_CRIADA', 'Solicitação de Despromoção Criada'), ('SOLICITACAO_DESPROMOCAO_APROVADA', 'Aprovação de Despromoção Registrada'), ('SOLICITACAO_DESPROMOCAO_CANCELADA', 'Solicitação de Despromoção Cancelada'), ('SOLICITACAO_EXCLUSAO_SUPERUSER_CRIADA', 'Solicitação de Exclusão de Superusuário Criada'), ('SOLICITACAO_EXCLUSAO_SUPERUSER_APROVADA', 'Aprovação de Exclusão de Superusuário Registrada'), ('SOLICITACAO_EXCLUSAO_SUPERUSER_CANCELADA', 'Solicitação de Exclusão de Superusuário Cancelada'), ('QUESTAO_CRIADA', 'Questão Criada'), ('QUESTAO_EDITADA', 'Questão Editada'), ('QUESTAO_DELETADA', 'Questão Deletada'), ('QUESTAO_RESTAURADA', 'Questão Restaurada'), ('QUESTAO_DELETADA_PERMANENTEMENTE', 'Questão Deletada Permanentemente'), ('ENTIDADE_CRIADA', 'Entidade Criada'), ('ASSUNTO_CRIADO', 'Assunto Criado'), ('NOTIFICACOES_RESOLVIDAS', 'Notificações Resolvidas'), ('NOTIFICACOES_REJEITADAS', 'Notificações Rejeitadas'), ('NOTIFICACOES_DELETADAS', 'Notificações Deletadas'), ('LOG_DELETADO', 'Log Deletado'), ('TENTATIVA_EXCLUSAO_MASSA_EXCEDIDA', 'Tentativa de Exclusão em Massa Excedida'), ('SIMULADO_CRIADO', 'Simulado Criado'), ('SIMULADO_EDITADO', 'Simulado Editado'), ('SIMULADO_DELETADO', 'Simulado Deletado'), ('CONQUISTA_CRIADA', 'Conquista Criada'), ('CONQUISTA_EDITADA', 'Conquista Editada'), ('CONQUISTA_DELETADA', 'Conquista Deletada'), ('AVATAR_CRIADO', 'Avatar Criado'), ('AVATAR_EDITADO', 'Avatar Editado'), ('AVATAR_DELETADO', 'Avatar Deletado'), ('BORDA_CRIADA', 'Borda Criada'), ('BORDA_EDITADA', 'Borda Editada'), ('BORDA_DELETADA', 'Borda Deletada'), ('BANNER_CRIADO', 'Banner Criado'), ('BANNER_EDITADO', 'Banner Editado'), ('BANNER_DELETADO', 'Banner Deletado'), ('CONFIG_XP_EDITADA', 'Configurações de XP Editadas'), ('SOLICITACAO_EXCLUSAO_LOG_CRIADA', 'Solicitação de Exclusão de Log Criada'), ('SOLICITACAO_EXCLUSAO_LOG_APROVADA', 'Aprovação de Exclusão de Log Registrada'), ('LOG_DELETADO_PERMANENTEMENTE', 'Log Deletado Permanentemente'), ('REGRA_RECOMPENSA_CRIADA', 'Regra de Recompensa Criada'), ('REGRA_RECOMPENSA_EDITADA', 'Regra de Recompensa Editada'), ('REGRA_RECOMPENSA_DELETADA', 'Regra de Recompensa Deletada'), ('RECOMPENSA_CONCEDIDA_MANUALMENTE', 'Recompensa Concedida Manualmente'), ('RECOMPENSA_REVOGADA', 'Recompensa Revogada')], max_length=50)),
                ('alvo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hash_log', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('alvo_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividades',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PromocaoSuperuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado_por', models.ManyToManyField(blank=True, related_name='promocoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Justificativa da Solicitação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_revisao', models.DateTimeField(blank=True, null=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('usuario_a_ser_excluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_de_exclusao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Exclusão',
                'verbose_name_plural': 'Solicitações de Exclusão',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
