# Generated by Django 5.2.5 on 2025-09-09 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('USUARIO_DELETADO', 'Usuário Deletado'), ('SOLICITACAO_EXCLUSAO_CRIADA', 'Solicitação de Exclusão Criada'), ('SOLICITACAO_EXCLUSAO_APROVADA', 'Solicitação de Exclusão Aprovada'), ('SOLICITACAO_EXCLUSAO_REJEITADA', 'Solicitação de Exclusão Rejeitada'), ('SOLICITACAO_EXCLUSAO_CANCELADA', 'Solicitação de Exclusão Cancelada'), ('QUESTAO_CRIADA', 'Questão Criada'), ('QUESTAO_EDITADA', 'Questão Editada'), ('QUESTAO_DELETADA', 'Questão Deletada')], help_text='A ação que foi realizada.', max_length=50)),
                ('alvo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, default=dict, help_text='Contexto adicional, como motivos ou justificativas.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('alvo_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ator', models.ForeignKey(blank=True, help_text='Usuário que realizou a ação.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividades',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
