# Generated by Django 5.2.5 on 2025-09-09 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_alter_logatividade_acao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logatividade',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logatividade',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logatividade',
            name='hash_log',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='logatividade',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='logatividade',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('USUARIO_DELETADO', 'Usuário Deletado'), ('PERMISSOES_ALTERADAS', 'Permissões de Usuário Alteradas'), ('USUARIO_PROMOVIDO_SUPERUSER', 'Usuário Promovido a Superuser'), ('USUARIO_DESPROMOVIDO_SUPERUSER', 'Usuário Despromovido de Superuser'), ('SOLICITACAO_EXCLUSAO_CRIADA', 'Solicitação de Exclusão Criada'), ('SOLICITACAO_EXCLUSAO_APROVADA', 'Solicitação de Exclusão Aprovada'), ('SOLICITACAO_EXCLUSAO_REJEITADA', 'Solicitação de Exclusão Rejeitada'), ('SOLICITACAO_EXCLUSAO_CANCELADA', 'Solicitação de Exclusão Cancelada'), ('QUESTAO_CRIADA', 'Questão Criada'), ('QUESTAO_EDITADA', 'Questão Editada'), ('QUESTAO_DELETADA', 'Questão Deletada'), ('ENTIDADE_CRIADA', 'Entidade Criada'), ('ASSUNTO_CRIADO', 'Assunto Criado'), ('NOTIFICACOES_RESOLVIDAS', 'Notificações Resolvidas'), ('NOTIFICACOES_REJEITADAS', 'Notificações Rejeitadas'), ('NOTIFICACOES_DELETADAS', 'Notificações Deletadas'), ('LOG_DELETADO', 'Log Deletado')], help_text='A ação que foi realizada.', max_length=50),
        ),
        migrations.AlterField(
            model_name='logatividade',
            name='detalhes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PromocaoSuperuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado_por', models.ManyToManyField(blank=True, related_name='promocoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
