# Generated by Django 5.2.5 on 2025-09-09 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_logatividade_deleted_at_logatividade_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('USUARIO_DELETADO', 'Usuário Deletado'), ('PERMISSOES_ALTERADAS', 'Permissões de Usuário Alteradas'), ('USUARIO_PROMOVIDO_SUPERUSER', 'Usuário Promovido a Superuser'), ('USUARIO_DESPROMOVIDO_SUPERUSER', 'Usuário Despromovido de Superuser'), ('SOLICITACAO_EXCLUSAO_CRIADA', 'Solicitação de Exclusão Criada'), ('SOLICITACAO_EXCLUSAO_APROVADA', 'Solicitação de Exclusão Aprovada'), ('SOLICITACAO_EXCLUSAO_REJEITADA', 'Solicitação de Exclusão Rejeitada'), ('SOLICITACAO_EXCLUSAO_CANCELADA', 'Solicitação de Exclusão Cancelada'), ('SOLICITACAO_PROMOCAO_CRIADA', 'Solicitação de Promoção Criada'), ('SOLICITACAO_PROMOCAO_APROVADA', 'Aprovação de Promoção Registrada'), ('QUESTAO_CRIADA', 'Questão Criada'), ('QUESTAO_EDITADA', 'Questão Editada'), ('QUESTAO_DELETADA', 'Questão Deletada'), ('ENTIDADE_CRIADA', 'Entidade Criada'), ('ASSUNTO_CRIADO', 'Assunto Criado'), ('NOTIFICACOES_RESOLVIDAS', 'Notificações Resolvidas'), ('NOTIFICACOES_REJEITADAS', 'Notificações Rejeitadas'), ('NOTIFICACOES_DELETADAS', 'Notificações Deletadas'), ('LOG_DELETADO', 'Log Deletado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='logatividade',
            name='ator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
