# Generated by Django 5.2.5 on 2025-09-10 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_despromocaosuperuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despromocaosuperuser',
            name='aprovado_por',
            field=models.ManyToManyField(blank=True, related_name='despromocoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='despromocaosuperuser',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10),
        ),
    ]
