# Generated by Django 5.2.5 on 2025-09-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_despromocaosuperuser_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('USUARIO_DELETADO', 'Usuário Deletado'), ('PERMISSOES_ALTERADAS', 'Permissões de Usuário Alteradas'), ('USUARIO_PROMOVIDO_SUPERUSER', 'Usuário Promovido a Superuser'), ('USUARIO_DESPROMOVIDO_SUPERUSER', 'Usuário Despromovido de Superuser'), ('SOLICITACAO_EXCLUSAO_CRIADA', 'Solicitação de Exclusão Criada'), ('SOLICITACAO_EXCLUSAO_APROVADA', 'Solicitação de Exclusão Aprovada'), ('SOLICITACAO_EXCLUSAO_REJEITADA', 'Solicitação de Exclusão Rejeitada'), ('SOLICITACAO_EXCLUSAO_CANCELADA', 'Solicitação de Exclusão Cancelada'), ('SOLICITACAO_PROMOCAO_CRIADA', 'Solicitação de Promoção Criada'), ('SOLICITACAO_PROMOCAO_APROVADA', 'Aprovação de Promoção Registrada'), ('SOLICITACAO_PROMOCAO_CANCELADA', 'Solicitação de Promoção Cancelada'), ('SOLICITACAO_DESPROMOCAO_CRIADA', 'Solicitação de Despromoção Criada'), ('SOLICITACAO_DESPROMOCAO_APROVADA', 'Aprovação de Despromoção Registrada'), ('QUESTAO_CRIADA', 'Questão Criada'), ('QUESTAO_EDITADA', 'Questão Editada'), ('QUESTAO_DELETADA', 'Questão Deletada'), ('ENTIDADE_CRIADA', 'Entidade Criada'), ('ASSUNTO_CRIADO', 'Assunto Criado'), ('NOTIFICACOES_RESOLVIDAS', 'Notificações Resolvidas'), ('NOTIFICACOES_REJEITADAS', 'Notificações Rejeitadas'), ('NOTIFICACOES_DELETADAS', 'Notificações Deletadas'), ('LOG_DELETADO', 'Log Deletado')], max_length=50),
        ),
    ]
