# Generated by Django 5.2.5 on 2025-09-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_alter_logatividade_acao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logatividade',
            name='is_archived',
        ),
    ]
