# Generated by Django 5.2.5 on 2025-09-10 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_remove_logatividade_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('USUARIO_DELETADO', 'Usuário Deletado'), ('PERMISSOES_ALTERADAS', 'Permissões de Usuário Alteradas'), ('USUARIO_PROMOVIDO_SUPERUSER', 'Usuário Promovido a Superuser'), ('USUARIO_DESPROMOVIDO_SUPERUSER', 'Usuário Despromovido de Superuser'), ('SOLICITACAO_EXCLUSAO_CRIADA', 'Solicitação de Exclusão Criada'), ('SOLICITACAO_EXCLUSAO_APROVADA', 'Solicitação de Exclusão Aprovada'), ('SOLICITACAO_EXCLUSAO_REJEITADA', 'Solicitação de Exclusão Rejeitada'), ('SOLICITACAO_EXCLUSAO_CANCELADA', 'Solicitação de Exclusão Cancelada'), ('SOLICITACAO_PROMOCAO_CRIADA', 'Solicitação de Promoção Criada'), ('SOLICITACAO_PROMOCAO_APROVADA', 'Aprovação de Promoção Registrada'), ('SOLICITACAO_PROMOCAO_CANCELADA', 'Solicitação de Promoção Cancelada'), ('SOLICITACAO_DESPROMOCAO_CRIADA', 'Solicitação de Despromoção Criada'), ('SOLICITACAO_DESPROMOCAO_APROVADA', 'Aprovação de Despromoção Registrada'), ('SOLICITACAO_EXCLUSAO_SUPERUSER_CRIADA', 'Solicitação de Exclusão de Superusuário Criada'), ('SOLICITACAO_EXCLUSAO_SUPERUSER_APROVADA', 'Aprovação de Exclusão de Superusuário Registrada'), ('SOLICITACAO_EXCLUSAO_SUPERUSER_CANCELADA', 'Solicitação de Exclusão de Superusuário Cancelada'), ('QUESTAO_CRIADA', 'Questão Criada'), ('QUESTAO_EDITADA', 'Questão Editada'), ('QUESTAO_DELETADA', 'Questão Deletada'), ('ENTIDADE_CRIADA', 'Entidade Criada'), ('ASSUNTO_CRIADO', 'Assunto Criado'), ('NOTIFICACOES_RESOLVIDAS', 'Notificações Resolvidas'), ('NOTIFICACOES_REJEITADAS', 'Notificações Rejeitadas'), ('NOTIFICACOES_DELETADAS', 'Notificações Deletadas'), ('LOG_DELETADO', 'Log Deletado')], max_length=50),
        ),
        migrations.CreateModel(
            name='ExclusaoSuperuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado_por', models.ManyToManyField(blank=True, related_name='exclusoes_superuser_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusoes_superuser_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusoes_superuser_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
