# Generated by Django 5.2.5 on 2025-09-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0020_exclusaologpermanente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('USUARIO_DELETADO', 'Usuário Deletado'), ('PERMISSOES_ALTERADAS', 'Permissões de Usuário Alteradas'), ('USUARIO_PROMOVIDO_SUPERUSER', 'Usuário Promovido a Superuser'), ('USUARIO_DESPROMOVIDO_SUPERUSER', 'Usuário Despromovido de Superuser'), ('SOLICITACAO_EXCLUSAO_CRIADA', 'Solicitação de Exclusão Criada'), ('SOLICITACAO_EXCLUSAO_APROVADA', 'Solicitação de Exclusão Aprovada'), ('SOLICITACAO_EXCLUSAO_REJEITADA', 'Solicitação de Exclusão Rejeitada'), ('SOLICITACAO_EXCLUSAO_CANCELADA', 'Solicitação de Exclusão Cancelada'), ('SOLICITACAO_PROMOCAO_CRIADA', 'Solicitação de Promoção Criada'), ('SOLICITACAO_PROMOCAO_APROVADA', 'Aprovação de Promoção Registrada'), ('SOLICITACAO_PROMOCAO_CANCELADA', 'Solicitação de Promoção Cancelada'), ('SOLICITACAO_DESPROMOCAO_CRIADA', 'Solicitação de Despromoção Criada'), ('SOLICITACAO_DESPROMOCAO_APROVADA', 'Aprovação de Despromoção Registrada'), ('SOLICITACAO_DESPROMOCAO_CANCELADA', 'Solicitação de Despromoção Cancelada'), ('SOLICITACAO_EXCLUSAO_SUPERUSER_CRIADA', 'Solicitação de Exclusão de Superusuário Criada'), ('SOLICITACAO_EXCLUSAO_SUPERUSER_APROVADA', 'Aprovação de Exclusão de Superusuário Registrada'), ('SOLICITACAO_EXCLUSAO_SUPERUSER_CANCELADA', 'Solicitação de Exclusão de Superusuário Cancelada'), ('QUESTAO_CRIADA', 'Questão Criada'), ('QUESTAO_EDITADA', 'Questão Editada'), ('QUESTAO_DELETADA', 'Questão Deletada'), ('QUESTAO_RESTAURADA', 'Questão Restaurada'), ('QUESTAO_DELETADA_PERMANENTEMENTE', 'Questão Deletada Permanentemente'), ('ENTIDADE_CRIADA', 'Entidade Criada'), ('ASSUNTO_CRIADO', 'Assunto Criado'), ('NOTIFICACOES_RESOLVIDAS', 'Notificações Resolvidas'), ('NOTIFICACOES_REJEITADAS', 'Notificações Rejeitadas'), ('NOTIFICACOES_DELETADAS', 'Notificações Deletadas'), ('LOG_DELETADO', 'Log Deletado'), ('TENTATIVA_EXCLUSAO_MASSA_EXCEDIDA', 'Tentativa de Exclusão em Massa Excedida'), ('SIMULADO_CRIADO', 'Simulado Criado'), ('SIMULADO_EDITADO', 'Simulado Editado'), ('SIMULADO_DELETADO', 'Simulado Deletado'), ('CONQUISTA_CRIADA', 'Conquista Criada'), ('CONQUISTA_EDITADA', 'Conquista Editada'), ('CONQUISTA_DELETADA', 'Conquista Deletada'), ('AVATAR_CRIADO', 'Avatar Criado'), ('AVATAR_EDITADO', 'Avatar Editado'), ('AVATAR_DELETADO', 'Avatar Deletado'), ('BORDA_CRIADA', 'Borda Criada'), ('BORDA_EDITADA', 'Borda Editada'), ('BORDA_DELETADA', 'Borda Deletada'), ('BANNER_CRIADO', 'Banner Criado'), ('BANNER_EDITADO', 'Banner Editado'), ('BANNER_DELETADO', 'Banner Deletado'), ('CONFIG_XP_EDITADA', 'Configurações de XP Editadas'), ('SOLICITACAO_EXCLUSAO_LOG_CRIADA', 'Solicitação de Exclusão de Log Criada'), ('SOLICITACAO_EXCLUSAO_LOG_APROVADA', 'Aprovação de Exclusão de Log Registrada'), ('LOG_DELETADO_PERMANENTEMENTE', 'Log Deletado Permanentemente')], max_length=50),
        ),
    ]
